name: Code Check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    name: ESLint Check
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.20.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
  
  l10n:
      runs-on: ubuntu-latest
      name: L10n Check
      steps:
        - name: Checkout code
          uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

        - name: Setup Node.js
          uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
          with:
            node-version: 22.20.0
            cache: npm

        - name: Install dependencies
          run: npm ci

        - name: Run sync-l10n
          run: node tools/sync-l10n --check

  dco:
    runs-on: ubuntu-latest
    name: DCO Check
    steps:
      - name: Run dco-check
        uses: christophebedard/dco-check@ec8bfc43106afe98b323ace9133650df10497e12 # 0.5.1
        with:
            python-version: '3.12'
            args: '--verbose'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
